src/core/i18n/localization/fr.ts, src/feature/Report/Company/CompanySearchResult.tsx
TRELLO-1322: prevent from reporting public company
=> TRELLO-1322: Prevent from reporting public company (#84)

src/feature/Report/ReportFlowContext.tsx
This reverts commit 21f129bf4bdaad42b05a074f84c8da5b7b282446.
=> Revert "Disable persistence of ReportDraft in localStorage"

src/core/model/ReportDraft.tsx
https://sentry.io/organizations/signalconso/issues/3534277060/?project=6259579&query=is%3Aunresolved&statsPeriod=7d
=> TRELLO-1415 fix Sentry error, some input detail seems sometimes undefined

src/components_feature/reportFlow/Company/Company.tsx, src/components_feature/reportFlow/Confirmation/Confirmation.tsx, src/components_feature/reportFlow/Details/Details.tsx, src/components_simple/reportFile/ReportFiles.tsx
* [TRELLO-2000] Fix attachements
* [TRELLO-2000] Fix attachements
=> MEP [TRELLO-2000] Fix attachements (#492)

src/analytic/AnalyticContext.tsx, src/analytic/analytic.ts, src/components_feature/reportFlow/Company/CompanySearchResult.tsx, src/components_feature/reportFlow/Problem/Problem.tsx, src/components_feature/reportFlow/Problem/ProblemInformation.tsx, src/components_feature/reportFlow/reportFlowStepper/ReportFlowStepper.tsx, src/plugins/matomo.ts
=> TRELLO-1948 : Matomo rework (#497)

src/components_feature/reportFlow/Confirmation/Confirmation.tsx, src/components_feature/reportFlow/reportFlowStepper/ReportFlowStepper.tsx, src/components_feature/reportFlow/reportFlowStepper/ReportFlowStepperHeader.tsx, src/model/ReportStep.ts
This reverts commit 0d7776c6d13e4cb2473711852f718f2153a76d0f.
=> MEP : Revert "TRELLO-1974 invert steps 2 && 3"

src/core/metadatas.ts, src/core/pagesDefinitions.ts
* Fix playground visible in production
* Fix playground visible in production
=> MEP Fix playground visible in production (#539)

src/components_simple/ScDialog.tsx, src/components_simple/SwitchLang.tsx, src/components_simple/reportFile/ReportFile.tsx, src/i18n/localization/en.ts, src/i18n/localization/fr.ts
* TRELLO-2076: dialog on switching lang with pending report
=> Trello 2076 (#544)

.github/workflows/gen-satisfaction-data.yml, .prettierignore, package.json, src/generate_stat_data/satisfaction.json, src/reusablePages/stats.tsx, src/scripts/gen-satisfaction-data.tsx
* Use OpenData API for User Ratings Fetching
* Add script to generate user satisfaction data
* Prevent build issues
* Prevent build issues_2
* Add GitHub Action Workflow
* Update script to fetch only essential data
* Display satisfaction rate
* Adjust user satisfaction display
* Adjust user satisfaction display_2
* Adjust user satisfaction display_2
---------
=> MEP Trello 2110 : display users satisfaction from Services Publics +

src/components_feature/playgroundComponents/PlaygroundOther.tsx, src/components_feature/playgroundComponents/PlaygroundPage.tsx, src/components_feature/reportFlow/Company/Company.tsx, src/components_feature/reportFlow/Company/CompanySearchResult.tsx, src/components_feature/reportFlow/Company/lib/BarcodeSearchResult.tsx, src/components_feature/reportFlow/Confirmation/Confirmation.tsx, src/components_simple/CompanyRecap/CompanyRecap.tsx, src/components_simple/CompanyRecap/ProductRecap.tsx, src/model/ReportDraft.ts, src/model/reportsFromApi.ts, src/test/fixture.ts
Also make the transformation ReportDraft -> ApiReportDraft a bit more explicit, field by field. We want to avoid passing or not passing a field by mistake.
=> Display the selected product (if present) on all relevent steps

src/components_feature/playgroundComponents/PlaygroundCompany.tsx, src/components_feature/playgroundComponents/PlaygroundOther.tsx, src/components_feature/playgroundComponents/PlaygroundPage.tsx, src/components_feature/reportFlow/Company/Company.test.tsx, src/components_feature/reportFlow/Company/Company.tsx, src/components_feature/reportFlow/Company/CompanyActionButtons.tsx, src/components_feature/reportFlow/Company/CompanyFilled.tsx, src/components_feature/reportFlow/Company/CompanySearchByBarcode.tsx, src/components_feature/reportFlow/Company/CompanySearchByIdentity.tsx, src/components_feature/reportFlow/Company/CompanySearchResult.tsx, src/components_feature/reportFlow/Company/InfluencerFilled.tsx, src/components_feature/reportFlow/Company/lib/BarcodeSearchResult.tsx, src/components_feature/reportFlow/Confirmation/Confirmation.tsx, src/components_simple/CompanyRecap/CompanyRecap.tsx, src/model/Company.ts, src/test/fixture.ts, src/utils/utils.ts
mostly :
- Split Company.tsx into multiple proper components (instead of creating a bunch of fonctions that are almost components inside the component)
- Rewrite the state/logic of CompanySearchByBarcode.tsx
- rework the two types CompanyDraft/CompanySearchResult to better match what actually happens at runtime
=> Refacto around Company.tsx, search by barcode, and types of Company

src/anomalies/Anomaly.ts, src/anomalies/checks/checkAnomaliesJson.ts, src/anomalies/yml/fr/01_Achat_en_Magasi/01_Un_probleme_qui/06_Moyens_de_paiem/_index.yaml, src/anomalies/yml/fr/03_Internet_hors_a/01_Un_influenceur_/03_Publicite_pour_.yaml, src/anomalies/yml/fr/06_Transport_en_co/01_Transports_en_c/01_Train/_index.yaml, src/anomalies/yml/fr/_imports/postreporthelper/controle-quantite-vendues.yaml, src/anomalies/yml/fr/_imports/postreporthelper/fiche-pratique-dlc.yaml, src/anomalies/yml/fr/_imports/postreporthelper/moyens-de-paiement.yaml, src/anomalies/yml/fr/_imports/postreporthelper/risques-trading-en-ligne.yaml, src/anomalies/yml/fr/_imports/postreporthelper/voyager-en-train.yaml, src/anomalies/yml/fr/_imports/subcategories/nourriture/01_Produit_perime/_index.yaml, src/anomalies/yml/fr/_imports/subcategories/nourriture/04_Probleme_de_qua/02_La_quantite_ann/_index.yaml, src/clients/SignalConsoApiClient.ts, src/components_feature/playgroundComponents/PlaygroundAcknoledgment.tsx, src/components_feature/reportFlow/Acknowledgement/Acknowledgement.tsx, src/components_feature/reportFlow/Acknowledgement/AcknowledgementLayout.tsx, src/model/CreatedReport.ts, src/scripts/gen-anomalies-json.ts, src/test/fixture.ts
* TRELLO-2325: add link after report to dgccrf site
=> TRELLO-2325: add link after report to dgccrf site (#755)

shared/anomalies/yml/fr/04_Travaux_et_reno/02_Renovation_ener/_index.yaml
notion de démarchage enlevée de l'exemple
=> TRELLO_2490_modif_ex_re

shared/anomalies/yml/fr/16_Animaux/01_Alimentation_Ma.yaml, shared/anomalies/yml/fr/16_Animaux/02_Soins.yaml, shared/anomalies/yml/fr/16_Animaux/03_Garde_danimaux.yaml, shared/anomalies/yml/fr/16_Animaux/04_Vendeur_danimau.yaml, shared/anomalies/yml/fr/16_Animaux/05_Assurance_sante.yaml, shared/anomalies/yml/fr/16_Animaux/_index.yaml
=> TRELLO2494_animaux

shared/anomalies/yml/fr/15_Secteur_de_la_s/01_Produit_de_sant/_index.yaml, shared/anomalies/yml/fr/15_Secteur_de_la_s/02_Professionnel_d/_index.yaml, shared/anomalies/yml/fr/15_Secteur_de_la_s/03_Professionnel_p/_index.yaml, shared/anomalies/yml/fr/15_Secteur_de_la_s/04_Hopital_Cliniqu/_index.yaml, shared/anomalies/yml/fr/15_Secteur_de_la_s/05_Pharmacie/_index.yaml, shared/anomalies/yml/fr/15_Secteur_de_la_s/06_Transport_sanit/_index.yaml, shared/anomalies/yml/fr/15_Secteur_de_la_s/07_Cure/_index.yaml, shared/anomalies/yml/fr/15_Secteur_de_la_s/08_Centre_de_sante/_index.yaml, shared/anomalies/yml/fr/15_Secteur_de_la_s/09_Jai_des_problem.yaml, shared/anomalies/yml/fr/15_Secteur_de_la_s/_index.yaml
modif mineures sur la catégorie santé
=> TRELLO-2495

shared/anomalies/yml/fr/14_Intoxication_al/01_Oui/_index.yaml, shared/anomalies/yml/fr/14_Intoxication_al/01_Sur_place.yaml, shared/anomalies/yml/fr/14_Intoxication_al/02_A_emporter.yaml, shared/anomalies/yml/fr/14_Intoxication_al/02_Non.yaml, shared/anomalies/yml/fr/14_Intoxication_al/03_En_livraison.yaml, shared/anomalies/yml/fr/14_Intoxication_al/04_Un_produit_prec.yaml, shared/anomalies/yml/fr/14_Intoxication_al/_index.yaml
Modifications mineures mais essentielles de l'arbo
=> [TRELLO-2501] intoxication

mobile-tools/src/app.test.ts, mobile-tools/src/config/config.ts, mobile-tools/src/services/categories.service.ts
* [TRELLO-2516] Add image & path to categories API
* [TRELLO-2516] Fix
=> MEP [TRELLO-2516] Add image & path to categories API (#879)

shared/anomalies/yml/fr/17_Demarchage_abus/01_Probleme_a_la_s/02_Je_suis_contact.yaml
modif de l'arbo démarchage abusif. Changement companykind, tags et detailinputs.
=> MEP TRELLO-2521_incoherence_arbo (#881)

website/src/components_feature/reportFlow/Company/CompanySearchResultComponent.tsx
Je ne merge pas de suite, car cela impacte à la fois l'ancienne recherche d'entreprise et la nouvelle.
Je voudrais laisser l'ancienne recherche d'entreprise intacte pendant une semaine, pour surveiller les stats.
=> add an autoscroll to Next button on CompanySearchResultComponent

website/src/app/[lang]/achat-site/page.tsx, website/src/app/[lang]/demarches-administratives/page.tsx, website/src/app/[lang]/dysfonctionnements-commandes-nourriture/page.tsx, website/src/app/[lang]/hygiene-douteuse-personnel-restauration/page.tsx, website/src/core/pagesDefinitions.ts, website/src/i18n/localization/en.ts, website/src/i18n/localization/fr.ts, website/src/landings/landingsData_fr.ts, website/src/reusablePages/manual_landings/achatSite.tsx, website/src/reusablePages/manual_landings/demarchesAdministratives.tsx, website/src/reusablePages/manual_landings/dysfonctionnementsCommandesNourriture.tsx, website/src/reusablePages/manual_landings/hygieneDouteusePersonnelRestauration.tsx
* [TRELLO-2657] Refacto 4 LPs
* [TRELLO-2657] Refacto 4 LPs
=> MEP [TRELLO-2657] Refacto 4 LPs (#944)

website/src/reusablePages/manual_landings/blackFridayAboFraisCaches.tsx, website/src/reusablePages/manual_landings/blackFridayColis.tsx, website/src/reusablePages/manual_landings/blackFridayDarkPatterns.tsx, website/src/reusablePages/manual_landings/blackFridayFausseReduction.tsx, website/src/reusablePages/manual_landings/blackFridayFauxStocks.tsx, website/src/reusablePages/manual_landings/blackFridayRetractation.tsx, website/src/reusablePages/manual_landings/blackFridaySav.tsx, website/src/reusablePages/manual_landings/blackFridaySitesFrauduleux.tsx
ajout des ancres sur les liens vers les fiches pratiques sur les LP du BF
=> TRELLO-2706: ajout des ancres sur les liens vers les fiches pratiques sur les LP du BF

website/src/reusablePages/manual_landings/blackFridayFausseReduction.tsx, website/src/reusablePages/manual_landings/blackFridayRetractation.tsx, website/src/reusablePages/manual_landings/blackFridaySav.tsx
Modif mineures de 3 LP. Demande Isabelle Collin.
=> TRELLO2723-modif_LP_BF

shared/anomalies/yml/fr/03_Internet_hors_a/01_Un_influenceur_/_index.yaml
=> Trello2733-exemples_influenceurs

website/src/landings/airtableLandings/airtableLandingsData_fr.ts, website/src/landings/manualLandings/ManualLandingsPageSwitch.tsx, website/src/landings/manualLandings/manualLandingsUtils.ts, website/src/reusablePages/manual_landings/faussesPromessesEcologiquesProduitsVendusEnMagasin.tsx, website/src/reusablePages/manual_landings/venteEnLigneProduitsFaussesPromessesEcologiques.tsx, website/src/reusablePages/manual_landings/venteProduitsPlastiqueUsageUniqueInternet.tsx, website/src/reusablePages/manual_landings/venteProduitsPlastiqueUsageUniqueMagasin.tsx
* [TRELLO-2722] Migrate 4 landing pages
* [TRELLO-2722] Generate landings
* [TRELLO-2722] Fix
=> MEP [TRELLO-2722] Migrate 4 landing pages (#969)

shared/anomalies/yml/fr/04_Travaux_et_reno/02_Renovation_ener/07_Demarchage_telephonique
duplication du parcours démarchage téléphonique pour de la réno énergétique dans la catégorie travaux et réno
=> TRELLO2747-duplication_demarchage_reno
